add the example from #17 to tests
According to the customer `yes_without_tls` does not work in some cases.
This adds one, from the exemplary config, in an attempt to cover it.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -117,10 +117,25 @@ errs_without_tls:
   script:
   - cd _debug
   - printf '0.0.0.0:8000\n\nupload /web/path {\n  to "/var/tmp"\n  yes_without_tls\n}\n' | tee Caddyfile
-  - ./ecaddy.upload* & sleep 0.2
-  - if ! pstree | grep -q -F ecaddy; then printf "expected it to run, instead it has exited\n"; exit 6; fi
-  - kill %1
+  - ./ecaddy.upload* & sleep 2
+  - if [[ ! -e /proc/$!/cmdline ]] && grep -q -F ecaddy /proc/$!/cmdline; then
+      printf "The process exited prematurely. It was expected to still run.\n";
+      exit 6;
+    fi
+  - kill $!
+
+  - printf ':8000 {\n  log stdout\n  errors {\n    log stderr\n  }\n  tls off\n  upload /web/path {\n    yes_without_tls\n    to "/var/tmp"\n  }\n}\n' | tee Caddyfile
+  - ./ecaddy.upload* & sleep 2
+  - if [[ ! -e /proc/$!/cmdline ]] && grep -q -F ecaddy /proc/$!/cmdline; then
+      printf "The process exited prematurely. It was expected to still run.\n";
+      exit 6;
+    fi
+  - kill $!
 
   - printf '0.0.0.0:8000\n\nupload /web/path {\n  to "/var/tmp"\n}\n' | tee Caddyfile
-  - ./ecaddy.upload* & sleep 0.2
-  - if pstree | grep -q -F ecaddy; then kill %1; printf "didn't err, but we expected it to\n"; exit 7; fi
+  - ./ecaddy.upload* & sleep 2
+  - if [[ -e /proc/$!/cmdline ]] && grep -q -F ecaddy /proc/$!/cmdline; then
+      printf "The start was expected to abort due to an error. That did not happen.\n";
+      kill $! || true;
+      exit 6;
+    fi
